<?xml version="1.0" ?>
<robot name="$(arg robotName)" xmlns:xacro="http://ros.org/wiki/xacro">

<!-- #### constants #### -->
<xacro:property name="deg_to_rad" value="0.017453"/>
<xacro:property name="PI" value="3.14"/>

<!-- #### body property #### -->
<xacro:property name="body_length" value=".45"/>
<xacro:property name="body_width" value=".45"/>
<xacro:property name="body_height" value=".45"/>

<!-- ####  leg property #### -->
<xacro:property name="leg_radius" value="0.025"/>
<xacro:property name="leg_length" value="0.32"/>
<xacro:property name="leg_mass" value="1"/>

<!-- ####  rod property #### -->
<xacro:property name="rod_radius" value="0.025"/>
<xacro:property name="rod_length" value="0.2"/>
<xacro:property name="rod_mass" value="1"/>

<!-- ####  Aruco property #### -->
<xacro:property name="aruco_width" value="0.25"/>
<xacro:property name="aruco_length" value="0.25"/>
<xacro:property name="aruco_height" value="0.01"/>
<xacro:property name="aruco_z" value="1."/>
<xacro:property name="aruco_mass" value="1"/>
<xacro:property name="edge_width" value="0.1"/>


<!-- ######################################### -->
<!-- begin           MACRO               begin -->
<!-- ######################################### -->

<xacro:macro name="cylinder_inertia" params ="m r h"> 
    <inertial> 
        <mass value="${m}"/> 
        <inertia ixx="${m*(3*r*r+h*h)/12}" ixy="0.0" ixz="0.0" 
                 iyy="${m*(3*r*r+h*h)/12}" iyz= "0.0" 
                 izz="${m*r*r/2}"/> 
     </inertial> 
 </xacro:macro>

<xacro:macro name="cuboid_inertia" params ="m w l h"> 
    <inertial> 
        <mass value="${m}"/> 
        <inertia ixx="${m*(w*w+h*h)/12}" ixy="0.0" ixz="0.0" 
                 iyy="${m*(l*l+h*h)/12}" iyz= "0.0" 
                 izz="${m*(w*w+l*l)/12}"/> 
     </inertial> 
 </xacro:macro>

<!-- #####  leg macro  ##### -->
<xacro:macro name="leg" params= "prefix suffix X1 Y1">
           
  <joint name="${prefix}_${suffix}_leg_joint" type="fixed">
    <parent link= "body"/>
    <child link= "${prefix}_${suffix}_leg"/>
    <origin xyz= "${(body_length/2)*X1} ${(body_width/2)*Y1}  ${leg_length/2}" rpy="0 0 0"/>
    <dynamics damping="0.0" friction="0.0"/>  
  </joint>

  <link name= "${prefix}_${suffix}_leg">
    <!-- usefule to visualize when debugging
    <visual>
      <origin rpy= "0 0 0" xyz= "0 0 0"/>
      <geometry>   
        <cylinder length="${leg_length}" radius= "${leg_radius}"/>
      </geometry>
      <material name= "light_black"/>
    </visual>
    -->
    <collision>
      <origin rpy= "0 0 0" xyz= "0 0 0"/>
      <geometry>
        <cylinder length="${leg_length}" radius= "${leg_radius}"/>
      </geometry>
    </collision>
    <xacro:cylinder_inertia m="${leg_mass}" r="${leg_radius}" h="${leg_length}"/>
  </link>
     
  <gazebo reference ="${prefix}_${suffix}_leg">
    <mu1 value=".005"/>
    <mu2 value=".005"/>
    <kp value="10000000.0"/>
    <kd value= "10.0"/>
    <maxVel>0.</maxVel>
    <minDepth>0.001</minDepth>
  </gazebo>
                 
</xacro:macro>

<!-- #####  Aruco macro  ##### -->
    <!-- Aruco facing four directions-->
<xacro:macro name="aruco" params= "prefix X1 Y1 Yaw aruco_id">
  <joint name="${prefix}_joint" type="fixed">
    <parent link= "body"/>
    <child link= "${prefix}_aruco"/>
    <origin xyz= "${(body_length/2)*X1} ${(body_width/2)*Y1} ${aruco_z}" rpy="${PI/2} 0 ${Yaw*PI/2}"/>
    <dynamics damping="0.0" friction="0.0"/>  
  </joint>

<!-- ##################################### -->
<!-- end           MACRO               end -->
<!-- ##################################### -->


  <link name= "${prefix}_aruco">
    <visual>
      <origin rpy= "0 0 0" xyz= "0 0 0"/>
      <geometry>   
          <box size="${aruco_length} ${aruco_width} ${aruco_height}"/>
      </geometry>
    </visual>
    <collision>
      <origin rpy= "0 0 0" xyz= "0 0 0"/>
      <geometry>
          <box size="${aruco_length} ${aruco_width} ${aruco_height}"/>
      </geometry>
    </collision>
    <xacro:cuboid_inertia m="${aruco_mass}" w="${aruco_width}" l="${aruco_length}" h="${aruco_height}"/>

  </link>

  <gazebo reference="${prefix}_aruco">
      <material>SOLab/aruco${aruco_id}</material>
  </gazebo>

    <!-- Back Board for white edges -->
  <joint name="${prefix}_whiteboarder_joint" type="fixed">
    <parent link= "body"/>
    <child link= "${prefix}_aruco_whiteboarder"/>
    <origin xyz= "${(body_length/2-aruco_height*1/3)*X1} ${(body_width/2-aruco_height*1/3)*Y1} ${aruco_z}" rpy="${PI/2} 0 ${Yaw*PI/2}"/>
    <dynamics damping="0.0" friction="0.0"/>  
  </joint>

  <link name= "${prefix}_aruco_whiteboarder">
    <visual>
      <origin rpy= "0 0 0" xyz= "0 0 0"/>
      <geometry>   
          <box size="${aruco_length+edge_width} ${aruco_width+edge_width} ${aruco_height}"/>
      </geometry>
    </visual>
    <collision>
      <origin rpy= "0 0 0" xyz= "0 0 0"/>
      <geometry>
          <box size="${aruco_length+edge_width} ${aruco_width+edge_width} ${aruco_height}"/>
      </geometry>
    </collision>
    <xacro:cuboid_inertia m="${aruco_mass}" w="${aruco_width+edge_width}" l="${aruco_length+edge_width}" h="${aruco_height}"/>
  </link>
  <gazebo reference="${prefix}_aruco_whiteboarder">
      <material>SOLab/WhiteGlow</material>
  </gazebo>

</xacro:macro>


  <!-- body-->
  <link name="body">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
          <mesh filename="package://amr_description/meshes/shelft/only_shelft_S.stl" scale="0.01 0.01 0.01"/>
      </geometry>
    </visual>

    <collision>
       <origin rpy="0 0 0" xyz="0 0 ${leg_length + body_height/2}"/>
       <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
       </geometry>
     </collision>
     <inertial>
         <mass value="1.0"/>
              <inertia ixx="1.3542" ixy="0.0"
                       iyy="1.3542" iyz="0.0"
                       izz="1.3542" ixz="0.0"/>
    </inertial>
   </link>

  <gazebo reference="body">
      <material>Gazebo/CeilingTiled</material>
  </gazebo>

<!-- #### 4 legs #### -->
  <xacro:leg prefix="right" suffix="front" X1="1" Y1="-1"/>
  <xacro:leg prefix="right" suffix="back" X1="-1" Y1="-1"/>
  <xacro:leg prefix="left" suffix="front" X1="1" Y1="1"/>
  <xacro:leg prefix="left" suffix="back" X1="-1" Y1="1"/>


<!-- #### B bottom #### -->
  <joint name="B_bot_joint" type="fixed">
    <parent link="body"/>
    <child link="B_bot" />
    <origin xyz="0 0 ${leg_length} " rpy="0 0 0"/>
  </joint>

  <link name="B_bot">
    <visual>
      <origin xyz="0.0 0 0.0" rpy="${PI} 0 ${PI/2}"/>
      <geometry>
        <cylinder length="${rod_length}" radius= "${rod_radius}"/>
      </geometry>
      <material name="light_black"/>
    </visual>

    <collision>
      <max_contacts>1</max_contacts>
      <origin xyz="0.0 0 0.0" rpy="${PI} 0 ${PI/2}"/>
      <geometry>
        <cylinder length="${rod_length}" radius= "${rod_radius}"/>
      </geometry>
    </collision>
    <xacro:cylinder_inertia m="${rod_mass}" r="${rod_radius}" h="${rod_length}"/>
  </link>

  <!-- Aruco spawn -->
  <xacro:aruco prefix="east" X1="0" Y1="-1" Yaw="0" aruco_id="203"/>
  <xacro:aruco prefix="west" X1="0" Y1="1" Yaw="0"  aruco_id="201"/>
  <xacro:aruco prefix="north" X1="1" Y1="0" Yaw="1" aruco_id="200"/>
  <xacro:aruco prefix="south" X1="-1" Y1="0" Yaw="1" aruco_id="202"/>

  <gazebo reference="B_bot">
      <mu1>0</mu1>
      <mu2>0</mu2>
      <kp>1000000</kp> 
      <kd>10</kd>
      <maxVel>0.</maxVel>
      <minDepth>0.001</minDepth>
      <material>Gazebo/Wood</material>
  </gazebo>


</robot>
